services:
  backend:
    image: backend:latest
    build:
      context: ./server
    ports:
      - 4040:4040
  frontend:
    image: frontend:latest
    build:
      context: ./client
    ports:
      - 5000:5173
    depends_on:
      - backend
