run:
	./gradlew bootRun

run-development:
	SPRING_PROFILE=development ./gradlew bootRun

run-prod:
	SPRING_PROFILE=production ./gradlew bootRun

lint:
	./gradlew checkstyleMain

test:
	./gradlew test

report:
	./gradlew jacocoTestReport