name: check backend
on:
  push:
    paths:
      - 'server'
      - '.github/workflows/backend-check.yml'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Linting Main
        run: ./gradlew checkstyleMain
      - name: Linting Test
        run: ./gradlew checkstyleTest
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Testing and generating report
        run: ./gradlew test jacocoTestReport
      - name: Send code coverage report
        uses: qltysh/qlty-action/coverage@v1
        with:
          token: {{secrets.QLTY_COVERAGE_TOKEN}}
          files: server/src/main/java/build/reports/jacoco/test/jacocoTestReport.xml
          format: jacoco
defaults:
  run:
    working-directory: ./server