name: check backend
on:
  push:
    paths:
      - 'server'
      - '.github/workflows/backend-check.yml'
#permissions:
#  actions: write
#  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Linting Main
        run: ./gradlew checkstyleMain
      - name: Linting Test
        run: ./gradlew checkstyleTest
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Testing and generating report
        run: |
          ./gradlew build
          ./gradlew test
          ./gradlew jacocoTestReport
      - name: Check if file exists
        id: check_file
        run: |
          if test -f "src/main/java/build/reports/jacoco/test/jacocoTestReport.xml"; then
          echo "::set-output name=result::true"
          else
          echo "::set-output name=result::false"
          fi
      - name: Do something if file exists
        if: steps.check_file.outputs.result == 'true'
        run: |
          echo "File exist!"
      - name: Do something else if file does not exist
        if: steps.check_file.outputs.result != 'true'
        run: |
          echo "File does not exist..."
      - name: Send code coverage report
        uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{secrets.QLTY_COVERAGE_TOKEN}}
          files: build/reports/jacoco/test/jacocoTestReport.xml
          add-prefix: server/src/main/java/
defaults:
  run:
    working-directory: ./server